# Generated by Django 5.2.17 on 2026-09-12 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_gameserver_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameserver',
            name='is_occupied',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('host_identifier', models.CharField(max_length=255)),
                ('second_player_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('server', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='api.gameserver')),
            ],
        ),
    ]
