# Generated by Django 5.2.17 on 2026-09-12 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_game_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(editable=False, max_length=8, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='host_identifier',
        ),
        migrations.RemoveField(
            model_name='game',
            name='second_player_identifier',
        ),
        migrations.AddField(
            model_name='game',
            name='host',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hosted_games', to='api.player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='second_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='joined_games', to='api.player'),
        ),
    ]
