# Generated by Django 5.2.17 on 2026-09-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_player_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameserver',
            old_name='ip_address',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='gameserver',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
