# Generated by Django 5.2.17 on 2026-09-29 11:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_ip_address_gameserver_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('health', models.PositiveSmallIntegerField()),
                ('armor', models.PositiveSmallIntegerField()),
                ('strength', models.PositiveSmallIntegerField()),
                ('equipment_slots', models.PositiveSmallIntegerField()),
                ('weapon_slots', models.PositiveSmallIntegerField()),
                ('min_count', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)])),
                ('max_count', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(10)])),
            ],
            options={
                'ordering': ['unit_type', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='api.species')),
            ],
            options={
                'ordering': ['species', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Army',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='armies', to='api.player')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='armies', to='api.species')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('army', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='api.army')),
            ],
            options={
                'ordering': ['army', 'position'],
            },
        ),
        migrations.CreateModel(
            name='UnitEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.entityprofile')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='api.unit')),
            ],
            options={
                'ordering': ['unit', 'position'],
            },
        ),
        migrations.CreateModel(
            name='UnitEntityEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveSmallIntegerField()),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='api.unitentity')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.equipment')),
            ],
            options={
                'ordering': ['entity', 'slot'],
            },
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('min_entities', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('max_entities', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('can_carry_heavy_weapon', models.BooleanField(default=False)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unit_types', to='api.species')),
            ],
            options={
                'ordering': ['species', 'name'],
            },
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.unittype'),
        ),
        migrations.AddField(
            model_name='entityprofile',
            name='unit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='api.unittype'),
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_heavy', models.BooleanField(default=False)),
                ('shots', models.PositiveSmallIntegerField()),
                ('strength', models.PositiveSmallIntegerField()),
                ('range', models.PositiveSmallIntegerField()),
                ('armor_penetration', models.PositiveSmallIntegerField()),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weapons', to='api.species')),
            ],
            options={
                'ordering': ['species', 'is_heavy', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UnitEntityWeapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveSmallIntegerField()),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weapons', to='api.unitentity')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.weapon')),
            ],
            options={
                'ordering': ['entity', 'slot'],
            },
        ),
        migrations.AddField(
            model_name='unit',
            name='heavy_weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.weapon'),
        ),
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.UniqueConstraint(fields=('species', 'name'), name='unique_equipment_per_species'),
        ),
        migrations.AddConstraint(
            model_name='army',
            constraint=models.UniqueConstraint(fields=('player', 'name'), name='unique_army_name_per_player'),
        ),
        migrations.AddConstraint(
            model_name='unitentityequipment',
            constraint=models.UniqueConstraint(fields=('entity', 'slot'), name='unique_equipment_slot_per_entity'),
        ),
        migrations.AddConstraint(
            model_name='unittype',
            constraint=models.UniqueConstraint(fields=('species', 'name'), name='unique_unit_type_per_species'),
        ),
        migrations.AddConstraint(
            model_name='entityprofile',
            constraint=models.UniqueConstraint(fields=('unit_type', 'name'), name='unique_profile_per_unit_type'),
        ),
        migrations.AddConstraint(
            model_name='weapon',
            constraint=models.UniqueConstraint(fields=('species', 'name'), name='unique_weapon_per_species'),
        ),
        migrations.AddConstraint(
            model_name='unitentityweapon',
            constraint=models.UniqueConstraint(fields=('entity', 'slot'), name='unique_weapon_slot_per_entity'),
        ),
    ]
