# Generated by Django 5.2.17 on 2026-09-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_weapon_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='unittype',
            name='transport_capacity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
