# Generated by Django 5.2.17 on 2026-09-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_entity_heavy_weapons'),
    ]

    operations = [
        migrations.AddField(
            model_name='unittype',
            name='max_heavy_weapons',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unittype',
            name='max_super_heavy_weapons',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
