# Generated by Django 5.2.17 on 2026-09-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_unit_heavy_weapon_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='unittype',
            name='can_capture_objectives',
            field=models.BooleanField(default=False),
        ),
    ]
