"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_99ut97a+qjco&q#^g9nh8rlm=5qv%f&rx%9twmc@t)q3$)yw0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Ohne diese Liste greift bei DEBUG=True nur der Django-Default
# (localhost/127.0.0.1/[::1]) -- das deckt den Browser (KEYCLOAK_REDIRECT_URI
# zeigt auf localhost:8000) und lokales `manage.py runserver` ab, aber nicht
# Aufrufe von anderen Containern im selben Docker-Netz, die den Servicenamen
# "backend" als Host senden (siehe game-server/register_instance.py, das
# RADISH_BACKEND_URL="http://backend:8000" gegen genau diesen Host aufruft).
ALLOWED_HOSTS = ["backend", "localhost", "127.0.0.1"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'api',
    'web',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Postgres statt sqlite (siehe docker-compose.yaml, Services "backend" +
# "backend-db"). Alle Werte per Umgebungsvariable ueberschreibbar; die
# Defaults passen zum "backend-db"-Service, der von aussen (ausserhalb von
# Docker, z.B. fuer ein lokales `manage.py`) unter localhost:5433 erreichbar
# ist -- deshalb DJANGO_DB_HOST default "localhost", nicht "backend-db"
# (das ist nur der Servicename im Docker-Netzwerk selbst).
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DJANGO_DB_NAME', 'radish'),
        'USER': os.environ.get('DJANGO_DB_USER', 'radish'),
        'PASSWORD': os.environ.get('DJANGO_DB_PASSWORD', 'radish'),
        'HOST': os.environ.get('DJANGO_DB_HOST', 'localhost'),
        'PORT': os.environ.get('DJANGO_DB_PORT', '5433'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Keycloak (OpenID Connect, Authorization Code Flow, serverseitig)
# https://docs.djangoproject.com/en/5.2/ref/settings/ -- eigener Block, kein
# Standard-Django-Setting. "radish-backend" ist ein confidential Client
# (siehe docker/keycloak/realm-radish.json); der Secret unten ist ein reiner
# Dev-Wert, passend zum admin/admin der Keycloak-Instanz -- fuer echten
# Betrieb ueber Umgebungsvariablen ersetzen.
KEYCLOAK_BASE_URL = os.environ.get("KEYCLOAK_BASE_URL", "http://localhost:8081")
# Serverseitige Aufrufe (Code-Tausch, userinfo, JWKS) laufen -- wenn das
# Backend selbst im Docker-Netzwerk laeuft -- besser ueber den internen
# Service-Namen "keycloak:8080" statt ueber den nach aussen veroeffentlichten
# Port. Der Browser sieht davon nichts: Redirects (Login, Logout) und die
# Issuer-Pruefung bleiben immer bei KEYCLOAK_BASE_URL, weil Keycloaks
# KC_HOSTNAME (siehe docker-compose.yaml) den Issuer ohnehin fix auf die
# externe URL setzt, unabhaengig davon, ueber welchen Pfad man Keycloak
# tatsaechlich erreicht hat. Ausserhalb von Docker (z.B. `manage.py runserver`
# auf dem Host) bleiben beide gleich, weil "keycloak" dort nicht aufloesbar ist.
KEYCLOAK_INTERNAL_BASE_URL = os.environ.get("KEYCLOAK_INTERNAL_BASE_URL", KEYCLOAK_BASE_URL)
KEYCLOAK_REALM = os.environ.get("KEYCLOAK_REALM", "radish")
KEYCLOAK_CLIENT_ID = os.environ.get("KEYCLOAK_CLIENT_ID", "radish-backend")
KEYCLOAK_CLIENT_SECRET = os.environ.get("KEYCLOAK_CLIENT_SECRET", "radish-backend-dev-secret")
KEYCLOAK_REDIRECT_URI = os.environ.get(
    "KEYCLOAK_REDIRECT_URI", "http://localhost:8000/api/login/callback/"
)
KEYCLOAK_POST_LOGOUT_REDIRECT_URI = os.environ.get(
    "KEYCLOAK_POST_LOGOUT_REDIRECT_URI", "http://localhost:8000/"
)


# DRF-Absicherung der uebrigen Endpunkte (servers/, client/*) ueber
# djangorestframework-simplejwt -- aber nicht im ueblichen Modus, in dem
# Django selbst Token-Paare ausstellt. Stattdessen validiert
# KeycloakJWTAuthentication (siehe api/authentication.py) direkt die von
# Keycloak ausgestellten Access-Tokens: Django ist reiner Resource-Server,
# das Login/Logout unter api/login/, api/logout/ bleibt unabhaengig davon
# session-basiert (siehe auth_views.py).
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "api.authentication.KeycloakJWTAuthentication",
    ],
}

SIMPLE_JWT = {
    # RS256 + JWK_URL: der Access-Token wird gegen Keycloaks oeffentliche
    # Schluessel geprueft, nicht gegen einen von Django gehaltenen Secret/Key.
    "ALGORITHM": "RS256",
    # JWKS-Abruf ist ein serverseitiger Aufruf -- ueber KEYCLOAK_INTERNAL_BASE_URL,
    # siehe Kommentar dort. ISSUER bleibt bewusst bei KEYCLOAK_BASE_URL (extern):
    # das muss exakt der "iss"-Klaim sein, den Keycloak in die Tokens schreibt.
    "JWK_URL": f"{KEYCLOAK_INTERNAL_BASE_URL}/realms/{KEYCLOAK_REALM}/protocol/openid-connect/certs",
    "ISSUER": f"{KEYCLOAK_BASE_URL}/realms/{KEYCLOAK_REALM}",
    # Keycloaks Access-Tokens tragen "sub" (nicht simplejwts uebliches
    # "user_id") und werden ueber User.username nachgeschlagen -- passend zu
    # get_or_create_user_from_claims() in api/keycloak.py.
    "USER_ID_CLAIM": "sub",
    "USER_ID_FIELD": "username",
    # simplejwt prueft standardmaessig eine eigene "token_type"-Klaim, die
    # nur bei selbst ausgestellten Tokens existiert. Keycloak-Tokens haben
    # stattdessen "typ": "Bearer" -- ohne diese Zeile wuerde jedes echte
    # Keycloak-Token als "falscher Token-Typ" abgelehnt.
    "TOKEN_TYPE_CLAIM": None,
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    # Keycloak-Access-Tokens tragen ohne eigenen Audience-Mapper GAR KEINE
    # "aud"-Klaim (kein automatisches "account" o.ae.). Deshalb hat der
    # Client "radish-web" in realm-radish.json einen expliziten
    # Audience-Mapper ("audience-radish-backend"), der "aud":
    # "radish-backend" in jedes Access-Token schreibt. PyJWT verlangt einen
    # passenden AUDIENCE-Wert, sobald ein Token ueberhaupt eine "aud"-Klaim
    # traegt -- ohne diese Uebereinstimmung schlaegt die Pruefung mit
    # "Invalid audience" fehl, auch bei einem sonst gueltigen Token.
    "AUDIENCE": "radish-backend",
}

